### ISSUE TITLE
Provide a list of products

### ISSUE THREAD

**Issue by celan** [SUSE/aimaas#8] opened 2021-09-02 13:53 UTC
At least the following information about a product should be provided:

Product/Deliverable
FCS (First Customer Shipment) date
General Support end
Long Term Support start date
Long Term Support end date
EOL (end of life) date
Products on which this product depends on

**Comment by crazyscientist** [comment] 2021-11-04 15:39
Duplicate of #2

Let's keep track of this in #2.

**Comment by crazyscientist** [comment] 2021-11-04 15:39
Duplicate of #2

**Closed** 2021-11-04 15:39 UTC

**Comment by crazyscientist** [comment] 2021-11-05 10:58
Oh, the last item "Products on which this product depends on" would be covered by the use case defined in #4
