### ISSUE TITLE
cannot search for use_case in the product catalog 

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/aimaas#179] opened 2023-12-18 13:30 UTC
![Screenshot_20231218_142942](https://github.com/SUSE/aimaas/assets/1029152/5fb47489-00be-40cc-81ba-88bac7dbdce2)

the "operator" field does not allow text input and appears to be a drop down with zero entries

**Comment by dirkmueller** [comment] 2023-12-18 13:30
is there a way to search for use case implementation also?

**Comment by crazyscientist** [comment] 2024-01-04 13:32
> is there a way to search for use case implementation also?

In this particular case the field `use_case` in the package catalog links to the "Use Case Implementation". If the filters would work (see #170) only this relation would be searchable.

**Comment by crazyscientist** [comment] 2024-01-04 13:32
Duplicate of #170

**Closed** 2024-01-04 13:33 UTC
