### ISSUE TITLE
Certain packages may have shorter lifecycle than the containing product/module

### ISSUE THREAD

**Issue by lpechacek** [SUSE/aimaas#28] opened 2021-11-29 10:51 UTC
This may be related to issue #13 in the general sense.

We've got sets of packages which have a shorter lifetime than the product where they are included. Examples below. The indication of a shorter package lifecycle is handled in the `zypper lifecycle` plugin and authoritative data is packaged in `lifecycle-data-*` packages. It would be cool if aimaas could serve as the central storage of lifecycle data from which scripts would generate both the `lifecycle-data-*` packages and the info web pages.

Examples:
* All packages at https://scc.suse.com/docs/lifecycle/sle/12/modules
* Live Patching https://www.suse.com/products/live-patching/current-patches (out of service now, data come from [company internal Git repo](https://gitlab.nue.suse.com/live-patching/sle-live-patching-data/-/blob/master/supported.csv))

References:
* FATE#320597: Introduce 'zypper lifecycle' to provide information about life cycle of individual products and packages  ([link to a company internal archive](https://w3.nue.suse.com/~lpechacek/fate-archive/320597.html))

**Comment by crazyscientist** [comment] 2022-09-29 09:05
Yes, looks like a duplicate to me.

duplicate of #13

**Comment by crazyscientist** [comment] 2022-09-29 09:06
Duplicate of #13

**Closed** 2022-09-29 09:06 UTC
