### ISSUE TITLE
Allow marking products to confidential

### ISSUE THREAD

**Issue by celan** [SUSE/aimaas#113] opened 2023-01-04 14:45 UTC
Certain products must not be shown to all users and therefore something like a state for "confidential" is necessary.

Non-released products might  be marked as "non-public" and all others public as they may be displayed in this context on a public page or similar.

**Comment by crazyscientist** [comment] 2023-01-04 15:35
> Certain products must not be shown to all users and therefore something like a state for "confidential" is necessary.

Maybe we can mark this issue as a duplicate of #69? After all, #69 already requests such a flag.

> Non-released products might be marked as "non-public" and all others public as they may be displayed in this context on a public page or similar.

I'm not sure what you want to achieve by this. Whatever application will send product data to this public page, can deduce the status of a product being released or not from the FCS date. Or do you suspect that there will be cases of products with FCS date, which in reality are not released?

**Comment by celan** [comment] 2023-01-12 12:15
Sorry, I wasn't aware that I opened an issue for that already.

FCS dates are not reliable and sometimes even there may be none.

**Comment by crazyscientist** [comment] 2023-01-16 09:27
Duplicate of #69

**Closed by crazyscientist** 2023-01-16 09:27 UTC
